### ISSUE TITLE
Issues when integrating with AWS lambda

### ISSUE THREAD

**Issue by pderaaij** [devopsfaith/krakend-lambda#2]
The past days we have been experimenting with KrakenD to replace our AWS Gateway API solution. However, we have run into a couple of problems. Regarding the lambda invocation, we run into the following problems.

 - The ClientContext needs to be a base64 encoded JSON object. Initially, I thought it was only a base64 encoded string as per #1. This is incorrect so I closed the PR.

 - The response that comes back from the AWS SDK library holds a structure that is not expanded by this library. It returns a JSON object with the fields `headers`, `statusCode` and `body`. In the current setup, this is passed thru directly as the response body. This should not be the case.

- When using `no-op` as content type a `nil` exception will be thrown. This is due to the fact that the `no-op` renderer expects an `Io` field on the response object and doesn't check for existence. 

- The documentation is unclear about the fact that a backend is required to make this work. We only got it working by adding a fake backend. In general, we wonder if a backend should be required in case of a lambda invocation.

- The documentation does not provide any context about the payload of the event that will be passed thru the Lambda. We didn't get it to work with a GET method as we were unable to get request information into the event object of our lambda function.

For us, it means we need to check out other options. Sharing this as a reference for others and perhaps the maintainers can improve on this.

**Comment by kpacha** [comment]
@pderaaij you're 100% right: the client context should be a base64 encoded json object. Do you have any suggestions regarding what should it contain?

regarding the other points:

- krakend is returning the response payload, so you can manipulate it using the regular data manipulation techniques (https://www.krakend.io/docs/backends/data-manipulation/).

- `no-op` pipes won't work with this component since it's already using a json decoder to unmarshal the response payload

- do you mean the `host` list for the backend? you can avoid adding it by setting a default one at the service (root) level. If you were talking about the `backends` list, it's because you could merge your lambda response with some other backend responses

- the payload is extracted using 2 different strategies, one for GET, one for POST. The payload will contain all the params defined for GET request (eg: the endpoint `/lambda/{a}/{b}` could create a payload such as `{"a": "foo", "b": "bar"}` when receiving the request `/lambda/foo/bar`) or the content of the body of a POST request

cheers

**Comment by kpacha** [comment]
as a quick fix, the new client context is a simple json struct with the krakend version
